### ISSUE TITLE
No weight or height limit for post terminals?

### ISSUE THREAD

**Issue by Djamuras** [mijora/omniva-opencart-3.0-ocmod#7]
It's seems this module doesnt have any weight or height limit?

**Comment by LithMage** [comment]
Hi, we could add in 30kg max limit, but no dimension checking. Currently completely rewriten module is being prepared, it will have by default enabled 30kg max limitation

**Comment by Djamuras** [comment]
New version will have dimension checking?

**Comment by LithMage** [comment]
No dimension in new version either, as its rather complicated and at best still only guessing what could be the dimensions of order. Also somewhat decent implentation would require third party library which requires certain PHP version (and this automatically is no good for as we are required to support older php versions)

**Comment by Djamuras** [comment]
How can i add weight limit on current version?

**Comment by Djamuras** [comment]
How can i add weight limit in current version for lockers?
